name: themed_application
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_modular: ^1.3.2
  flutter_mobx: ^1.1.0
  mobx: ^1.2.0
  shared_preferences: ^0.5.7+2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
